name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  example-gh-job:
    runs-on: ubuntu-latest
    steps:
      - name: First steps
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run ci.py
        run: |
          run pip install -r requirements.txt
          python ci.py
          
